# Generated by Django 3.1.2 on 2022-01-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='название')),
                ('price', models.IntegerField(verbose_name='цена')),
                ('image', models.TextField(verbose_name='картинка')),
                ('release_date', models.DateField(verbose_name='дата релиза')),
                ('lte_exists', models.BooleanField()),
                ('slug', models.SlugField(max_length=250)),
            ],
        ),
    ]
